# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is an application:  

QT += 		xml core gui

SUBDIRS =	src/commands \
	    	src/dom \
		src/dockwidgets \
		src/focreator \
		src/nodefo \
		src/viewitemsabs \
		src/viewitems \
		src/viewitems/foblock \
		src/viewitems/fotable \
		src 

CONFIG += 	debug \
        	warn_on 

TEMPLATE = 	subdirs

HEADERS += 

SOURCES += 

TARGET = 	qxsl-fo