######################################################################
# Automatically generated by qmake (2.01a) mar 10. gio 01:03:47 2008
######################################################################

TEMPLATE = app
TARGET = xx
DEPENDPATH += . 
INCLUDEPATH += .

DESTDIR	+= ./

CONFIG   +=  qt thread warn_off release console


# Input
HEADERS += qvcursor.h 
SOURCES += main.cpp \
           qvcursor.cpp
