######################################################################
# Automatically generated by qmake (2.01a) ven 15. ago 13:58:18 2008
######################################################################

TEMPLATE = app
TARGET = xx
DEPENDPATH += .
INCLUDEPATH += .

MOC_DIR = build/.moc
RCC_DIR = build/.rcc
OBJECTS_DIR = build/.obj


CONFIG +=  qt release warn_off console
DESTDIR	+= ./




# Input
HEADERS += FoColorName.h
SOURCES += FoColorName.cpp main.cpp
