######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 17 20:51:03 2007
######################################################################

TEMPLATE = app
TARGET = xx
DEPENDPATH += .
INCLUDEPATH += .

DESTDIR	+= ./

CONFIG += console
CONFIG   += qt warn_off debug

# Input
SOURCES += main.cpp
